services:
  web:
    container_name: foodflow-frontend
    build: .
    ports:
      - "4173:4173"
      - "80:80"
    volumes:
     - .:/app
     - ./node_modules:/app/node_modules
    env_file:
      - .env