services:
  web:
    container_name: foodflow-frontend
    build:
      context: .
      target: production
    ports:
      - "80:80"
    env_file:
      - .env
    restart: unless-stopped

  web-dev:
    profiles: ["dev"]
    container_name: foodflow-frontend-dev
    build:
      context: .
      target: development
    ports:
      - "4173:4173"
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["pnpm", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]
    env_file:
      - .env